//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
